INFO 2025-10-20 00:13:30,017 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:14:54,379 autoreload C:\Users\user\backendCapstoneProject\blogging_platform\blogging_platform\settings.py changed, reloading.
INFO 2025-10-20 00:14:56,401 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:15:36,958 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:16:44,069 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:19:17,229 autoreload Watching for file changes with StatReloader
WARNING 2025-10-20 00:19:27,249 log Not Found: /
WARNING 2025-10-20 00:19:27,250 basehttp "GET / HTTP/1.1" 404 3535
WARNING 2025-10-20 00:19:27,622 log Not Found: /favicon.ico
WARNING 2025-10-20 00:19:27,625 basehttp "GET /favicon.ico HTTP/1.1" 404 3586
INFO 2025-10-20 00:19:41,214 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2025-10-20 00:19:41,648 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4188
INFO 2025-10-20 00:19:42,355 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-10-20 00:19:42,388 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-10-20 00:19:42,392 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-10-20 00:19:42,398 basehttp "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-10-20 00:19:42,416 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-10-20 00:19:42,477 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-10-20 00:19:42,516 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-10-20 00:19:54,517 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-10-20 00:19:54,637 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 00:19:54,765 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-10-20 00:19:54,803 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-10-20 00:19:54,804 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
WARNING 2025-10-20 00:20:22,857 log Not Found: /
WARNING 2025-10-20 00:20:22,863 basehttp "GET / HTTP/1.1" 404 3535
INFO 2025-10-20 00:21:50,678 autoreload C:\Users\user\backendCapstoneProject\blogging_platform\blogging_platform\urls.py changed, reloading.
INFO 2025-10-20 00:21:54,097 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:26:09,199 autoreload Watching for file changes with StatReloader
ERROR 2025-10-20 00:26:17,984 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_blogpost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 765, in home_view
    'total_posts': BlogPost.objects.filter(status='published').count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_blogpost
ERROR 2025-10-20 00:26:18,020 basehttp "GET / HTTP/1.1" 500 138950
INFO 2025-10-20 00:26:55,659 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 00:26:55,893 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:55,929 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-20 00:26:55,942 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:55,977 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,026 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,047 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,053 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,210 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,214 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
ERROR 2025-10-20 00:27:02,090 log Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\options.py", line 2024, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\options.py", line 867, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.queryset = self.get_queryset(request)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 545, in get_queryset
    ) = self.get_filters(request)
        ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 216, in get_filters
    spec = field_list_filter_class(
        field,
    ...<4 lines>...
        field_path=field_path,
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
        field, request, params, model, model_admin, field_path=field_path
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1083, in get_choices
    (choice_func(x), str(x)) for x in qs
                                      ^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_category
ERROR 2025-10-20 00:27:02,127 basehttp "GET /admin/blog/blogpost/ HTTP/1.1" 500 223287
INFO 2025-10-20 00:45:04,860 autoreload Watching for file changes with StatReloader
ERROR 2025-10-20 00:45:22,813 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_blogpost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 765, in home_view
    'total_posts': BlogPost.objects.filter(status='published').count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_blogpost
ERROR 2025-10-20 00:45:22,850 basehttp "GET / HTTP/1.1" 500 138950
INFO 2025-10-20 00:47:28,685 autoreload Watching for file changes with StatReloader
ERROR 2025-10-20 00:47:37,973 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 770, in home_view
    return render(request, 'blog/home.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1610, in execute_sql
    sql, params = self.as_sql()
                  ~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 766, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ~~~~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases or bool(combinator),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 86, in pre_sql_setup
    order_by = self.get_order_by()
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 490, in get_order_by
    for expr, is_ref in self._order_by_pairs():
                        ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 473, in _order_by_pairs
    yield from self.find_ordering_name(
               ~~~~~~~~~~~~~~~~~~~~~~~^
        field,
        ^^^^^^
        self.query.get_meta(),
        ^^^^^^^^^^^^^^^^^^^^^^
        default_order=default_order,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1120, in find_ordering_name
    (OrderBy(transform_function(t, alias), descending=descending), False)
             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1924, in transform
    return self.try_transform(wrapped, name)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1458, in try_transform
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Unsupported lookup 'count' for BigAutoField or join on the field not permitted, perhaps you meant contains?
ERROR 2025-10-20 00:47:38,009 basehttp "GET / HTTP/1.1" 500 216793
INFO 2025-10-20 00:48:28,512 autoreload C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py changed, reloading.
INFO 2025-10-20 00:48:30,818 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:48:58,767 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:49:25,304 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:50:28,505 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:50:37,193 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 00:50:37,777 basehttp "GET /static/blog/css/base.css HTTP/1.1" 200 13721
INFO 2025-10-20 00:50:37,791 basehttp "GET /static/blog/js/main.js HTTP/1.1" 200 1633
INFO 2025-10-20 00:50:37,792 basehttp "GET /static/blog/css/components.css HTTP/1.1" 200 5938
INFO 2025-10-20 01:01:11,312 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 01:01:16,574 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 01:01:16,865 basehttp "GET /static/blog/css/components.css HTTP/1.1" 304 0
INFO 2025-10-20 01:01:16,879 basehttp "GET /static/blog/js/main.js HTTP/1.1" 304 0
INFO 2025-10-20 01:01:17,086 basehttp "GET /static/blog/css/base.css HTTP/1.1" 200 13909
ERROR 2025-10-20 01:01:49,936 log Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 1029, in post_create_view
    return render(request, 'blog/post_form.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/post_form.html
ERROR 2025-10-20 01:01:49,953 basehttp "GET /create/ HTTP/1.1" 500 97952
INFO 2025-10-20 01:02:17,975 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 01:02:18,062 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,091 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,092 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,109 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,112 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,118 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,123 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,171 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,172 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-10-20 01:02:40,245 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 01:04:31,923 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 01:04:32,273 basehttp "GET /static/blog/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 01:09:01,946 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 01:09:02,210 basehttp "GET /static/blog/css/components.css HTTP/1.1" 304 0
INFO 2025-10-20 01:09:02,239 basehttp "GET /static/blog/css/base.css HTTP/1.1" 200 15961
INFO 2025-10-20 01:09:02,274 basehttp "GET /static/blog/js/main.js HTTP/1.1" 304 0
